version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: shipflow_db
      POSTGRES_USER: michael
      POSTGRES_PASSWORD: alejandro
    ports:
      - "5432:5432"