spring:
  application:
    name: alejandro_michael_shipflow

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/shipflow_db
    driver-class-name: org.postgresql.Driver
    username: michael
    password: alejandro

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect